modLoader="javafml" 
loaderVersion="[36,)" 
issueTrackerURL="https://github.com/noobanidus/empty/issues"
license="https://github.com/noobanidus/empty/blob/master/LICENSE"
[[mods]] 
modId="empty" 
version="${version}"
displayName="Empty"
displayURL="https://minecraft.curseforge.com/projects/empty"
credits=""
authors="Noobanidus"
description='''
Empty serializers for recipes, etc, that make data pack recipe deletion simpler.
'''
[[dependencies.empty]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.empty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
